# Generated by Django 4.0.2 on 2022-04-07 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoryDetails',
            new_name='CategoryMinors',
        ),
    ]
