# Generated by Django 4.0.2 on 2022-04-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_categorydetails_categoryminors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categorys',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='CategoryMinors',
            new_name='CategoryMinor',
        ),
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
    ]
