# Generated by Django 4.0.2 on 2022-04-08 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_categorys_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category_minor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoryminor'),
        ),
    ]
