# Generated by Django 4.0.2 on 2022-04-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_category_minor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='gps',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
